services/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField

# EXAMPLE | Api Route for Getting the weather data
@dashboard.route('/altGetWeatherData', methods=['GET'])
def altGetWeatherData():
	url = "https://api.darksky.net/forecast/6f5d06c8550c54d468601ad72af413fd/33.9052,-84.0084"
	
	# Does a GET request to get the weather data
	r = requests.get(url)
	print (r.status_code)

	# Checks the request status to see if it pass
	if r.status_code == 200:
		apiData = r.json()
		return jsonify({'data': apiData, 'error':''})
	else:
		return jsonify({'error':'Failure to retreive weather data!'})

app.py
from flask import Flask, Blueprint, render_template, jsonify, url_for, request, redirect, session
from dash.views import dashboard
from contact.views import contact

# Sets up a new flask app
Portfolio = Flask(__name__)

# Registers blueprints
Portfolio.register_blueprint(dashboard)
Portfolio.register_blueprint(contact)

@Portfolio.route('/')
def Homepage():
    return render_template('home.html', name='Saher')

@Portfolio.route('/AboutMe')
def AboutMe():
    return render_template('aboutme.html', name='Saher')

@Portfolio.route('/MyPortfolio')
def ShowPortfolio():
    return render_template('portfolio.html', name='Saher')

if __name__ == '__main__':
    Portfolio.run(debug=True)

contact/views.py
import os, requests
from flask import Flask, Blueprint, render_template, jsonify, url_for, request, redirect, session
from model import connectToDB

contact = Blueprint('contact', __name__)

# Displays the Contact Form
@contact.route('/ContactForm', methods=['GET', 'POST'])
def ContactForm():
	return render_template('contactform.html', name='Saher')

#Api Route for Contact Form
@contact.route('/handleContactForm', methods=['POST'])
def handleContactForm():
	try:
		# Get front end data
		ajax_data = request.get_json()
		print(ajax_data)

		# Connect to my database and correct collection
		db = connectToDB()
		contact_data = db.contact_data

		#Insert form data into db
		contact_data.insert_one(ajax_data)

		# Return success message
		return jsonify('Successful!')
	except Exception as e:
		print(str(e))
		return jsonify('Failed')

dash/views.py
import os, requests
from flask import Flask, Blueprint, render_template, jsonify, url_for, request, redirect, session
from .apiCalls import getWeatherData

dashboard = Blueprint('dashboard', __name__, template_folder='templates', static_folder='static')


# EXAMPLE | Displays the Python Weather Widget
@dashboard.route('/showWeatherData', methods=['GET'])
def showWeatherData():
	weatherData = getWeatherData()
    
	if 'data' in weatherData:
		weatherData = weatherData['data']
		return render_template('weatherWidget.html', data=weatherData)
	else:
		weatherError = weatherData['error']
		return render_template('weatherWidget.html', error=weatherError)

# EXAMPLE | Displays the AJAX Weather Widget
@dashboard.route('/showAltWeatherData', methods=['GET'])
def showAltWeatherData():
    return render_template('weatherWidget2.html')

@dashboard.route('/showNewsData', methods=['GET'])
def showNewsData():
	return render_template('news.html')

@dashboard.route('/newsData', methods=['GET'])
def newsData(): 
	x = requests.get('http://newsapi.org/v2/top-headlines?country=us&apiKey=0a27659cc5a24df2bfdda7d5201f201c')
	newsData = x.json() 
	print(newsData)
	return jsonify(newsData)

@dashboard.route('/showJobData', methods=['GET'])
def showJobData():
	return render_template('jobs.html')

templates/aboutme.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <title>About Me</title>
    </head>
    <body>
        <div>
            <h1>About Me</h1>
            <h2>I am an aspiring developer in hopes to reach an audience that is interested in this app in order to help themselves. I have a passion for creating and analyzing data. </h2>            <p>Click on the links below to find out more!</p>
            <p id="example"></p>
            <img src="{{ url_for('static', filename='jpg/me.jpg') }}" width="300px" height="400px"><br>
            <a href="{{ url_for('Homepage') }}">Home Page</a>
            <a href="{{ url_for('ShowPortfolio') }}">Portfolio</a>
            <a href="{{ url_for('contact.ContactForm') }}">Contact Form</a>
        </div>
    </body>
    <script>
        var element_text = $(".test").text();  

        $("#example").text(element_text);
        $("#example").css({"font-size":"25px", "color":"purple"});

        $('#example').click(function() {
            $("div").remove();
        });
    
    </script> 
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News Page</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
</head>
<body>
    <h1>Display current news</h1>

    <div>
        <p>News Data is:</p>
        <table style='border:1px solid red;'>
            {% for item in infodata %}
                <tr>
                    <td>{{author}}</td>
                    <td>{{title}}</td>
                </tr>
            {% endfor %}
        </table>
        
    </div>


    <div class='AlternateNewsData'></div>

    <br>

    <div>Error</div>
    <div class='error'>{{error}}</div>

</body>
</html>

<script>
    var BaseURL = window.location.origin;
    var newsURL = BaseURL + "/altGetNewsData"

    $.ajax({
        method:'GET',
        url: newsURL,
        contentType: 'application/json',
        success: function(msg) {
            console.log(msg);

            if ('infodata' in msg) {
                $('.AlternateNewsData').text(msg['infodata']['author']);
            } else {
                alert('Failed to load news data!');
                $('.error').text(msg['error']);
                $('.error').css({'color':'red'});
            }
        }
        , error: function(error) {
            console.log(error);
            alert(error);
        }
    })
</script>

templates/home.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        <title>Homepage</title>
        <style>
            #panel, #flip{
                padding: 5px;
                text-align: center;
                background-color: white;
                border: solid 1px gray;
                }
                
            #panel{
                padding: 50px;
                display: none;
                }

               
            .flex-container{
                display: flex;
                background-color: lightblue;
                }
                
            .flex-container > div{
                background-color: #f1f1f1;
                margin: 10px;
                padding: 20px;
                font-size: 30px;
                }
        </style>
    </head>
    <body>
        <button id='ClickBtn'>Click</button id><br><br>
        <div id="div1" style="width:80px;height:80px;display:none;background-color:white;"></div><br>
        <div id="div2" style="width:80px;height:80px;display:none;background-color:black;"></div><br>
        <div id="div3" style="width:80px;height:80px;display:none;background-color:gray;"></div>
       
        <div id="flip">Click for slide</div>
        <div id="panel">Hello!</div>
        
        <div>
            <h1>Welcome to my page!</h1>

            <div class="flex-container">
                <div>App 1</div>
                <div>App 2</div>
                <div>App 3</div>
            </div>
            
            <p>Click on the links below to find out more!</p>
            <a href="{{ url_for('AboutMe') }}">About Me</a>
            <a href="{{ url_for('ShowPortfolio') }}">Portfolio</a>
            <a href="{{ url_for('contact.ContactForm') }}">Contact Form</a>
        </div>
    </body>
    <script>
        $('#ClickBtn').off('click').on('click', function(){
            console.log('HEY ITS ME!');
            $("#div1").fadeIn();
            $("#div2").fadeIn();
            $("#div3").fadeIn();
        });
    </script>   
    <script> 
        $('document').ready(function(){
            $("#flip").click(function(){
            $("#panel").slideDown("slow");
            });
        });
    </script>  
</html>

templates/login.html
<head>
    <body>
        <form action="/login" method="POST">
            <div class="login">
                <div class="screen">
                    <div class="title">
                        <h1>Login</h1>
                    </div>
                    <div class="form">
                    <div class="control-group">
                        <input type="text" class="loginfield" value="" placeholder="username" name="username">
                        <label class="icon user" for="loginname"></label></div>
                        <div class="control-group">
                            <input type="password" class="loginfield" value="" placeholder="password" name="password">
                            <label class="icon lock" for="loginpass"></label></div>
                            <input type="submit" value="Log in" class="btn btn-primary btn-large btn-block">
                    </div>
                </div>
            </div>
        </form>
        
        <a id="google-button" class="btn btn-block btn-social btn-google">
            <i class="google"></i> Sign in with google
        </a>
        
        <script>
        $('#google-button').on('click', function() {
            OAuth.initialize('708386988448-267vhjb7fs77gb2fitjd82262ubi0lm1.apps.googleusercontent.com');
            OAuth.popup('google').then(google => {
                console.log(google);
                console.log(google.me());
            });
        })
        </script>
    </body>
</head>

templates/portfolio.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        <title>Homepage</title>
    </head>
    <body>
        <div>
            <h1>Welcome to my page!</h1>     
            <p>Click on the links below to find out more!</p>
            <a href="{{ url_for('Homepage') }}">Home Page</a>
            <a href="{{ url_for('AboutMe') }}">About Me</a>
            <a href="{{ url_for('contact.ContactForm') }}">Contact Form</a>
        </div>
    </body>
</html>